# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Email-LocalDelivery
version:      0.09
version_from: LocalDelivery.pm
installdirs:  site
requires:
    Email::FolderType:             0.7
    Email::Simple:                 1.92
    File::Path::Expand:            1.01
    Test::More:                    0.47

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.24
